#!/bin/bash
set -euo pipefail

# Dev install: point SwiftBar at your local qmd.30s.ts source so edits
# to your working copy go live on the next 30s poll, with no rebuild.
# This is the source install path (requires Deno on $PATH), not the
# compiled binary install.
#
# Why a wrapper and not a symlink: qmd.30s.ts uses bare imports
# (@std/path, etc.) resolved through the repo deno.json import map.
# Deno discovers that import map by walking up from the entry file's
# directory. A symlink in the plugin folder makes the entry resolve to
# the plugin folder, where there is no deno.json, so every import fails
# ("Import @std/path not a dependency"). Instead we drop a tiny wrapper
# in the plugin folder that execs the real qmd.30s.ts by its absolute
# path. Executing the real path fires its own shebang (so all the
# --allow-* flags come for free, no drift) and makes the entry resolve
# inside the repo, where deno.json is found. The .ts stays the single
# source of truth: edits to it are live on the next poll.
#
# Usage:
#   scripts/dev-install.sh              # install the dev wrapper
#   scripts/dev-install.sh --uninstall  # remove the dev wrapper

SOURCE_NAME="qmd.30s.ts"   # the live source we delegate to
ENTRY_NAME="qmd.30s.sh"    # the wrapper SwiftBar runs (30s refresh)
LEGACY_LINK_NAME="qmd.30s.ts"  # symlink from an earlier version of this script
MARKER="# qmd-swiftbar-dev-wrapper (generated by scripts/dev-install.sh)"

# SwiftBar's plugin folder is user-configurable, so do not hardcode it.
# It is stored in SwiftBar's preferences under the PluginDirectory key
# (bundle id com.ameba.SwiftBar). Read it; fall back to the documented
# default only if SwiftBar has never been configured.
DEFAULT_PLUGIN_DIR="$HOME/Library/Application Support/SwiftBar/Plugins"
PLUGIN_DIR=$(defaults read com.ameba.SwiftBar PluginDirectory 2>/dev/null || true)
if [ -z "${PLUGIN_DIR:-}" ]; then
  PLUGIN_DIR="$DEFAULT_PLUGIN_DIR"
  echo "NOTE: SwiftBar plugin directory not set in preferences;"
  echo "falling back to default: $PLUGIN_DIR"
fi

# Resolve the repo root from this script's own location so the script
# works regardless of the caller's current directory.
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
SOURCE="$REPO_ROOT/$SOURCE_NAME"
ENTRY="$PLUGIN_DIR/$ENTRY_NAME"
LEGACY_LINK="$PLUGIN_DIR/$LEGACY_LINK_NAME"

restart_hint() {
  echo "Restart SwiftBar (Cmd-Q in the SwiftBar menu, then relaunch) to apply."
}

# Remove a prior dev symlink left by the earlier (broken) version of
# this script, but only if it actually points back at this repo.
remove_legacy_link() {
  if [ -L "$LEGACY_LINK" ] && [ "$(readlink "$LEGACY_LINK")" = "$SOURCE" ]; then
    rm "$LEGACY_LINK"
    echo "Removed stale dev symlink: $LEGACY_LINK"
  fi
}

# A file is "ours" only if it carries our marker. This keeps us from
# deleting or clobbering a real binary-install wrapper of the same name.
is_our_wrapper() {
  [ -f "$1" ] && grep -qF "$MARKER" "$1"
}

# --uninstall: remove the wrapper (and any legacy symlink) we created.
if [ "${1:-}" = "--uninstall" ]; then
  removed=0
  if is_our_wrapper "$ENTRY"; then
    rm "$ENTRY"
    echo "Removed dev wrapper: $ENTRY"
    removed=1
  elif [ -e "$ENTRY" ]; then
    echo "Not removing $ENTRY: it is not a dev wrapper (no marker)."
    echo "Leaving it untouched. Remove it by hand if that is intended."
  fi
  if [ -L "$LEGACY_LINK" ] && [ "$(readlink "$LEGACY_LINK")" = "$SOURCE" ]; then
    rm "$LEGACY_LINK"
    echo "Removed stale dev symlink: $LEGACY_LINK"
    removed=1
  fi
  if [ "$removed" -eq 1 ]; then
    restart_hint
  else
    echo "Nothing to remove."
  fi
  exit 0
fi

if [ ! -f "$SOURCE" ]; then
  echo "ERROR: source plugin not found at $SOURCE"
  exit 1
fi

# Deno is required for the source install path (the shebang runs the
# plugin via deno). Warn but do not block: you may just want the wrapper
# in place before installing Deno.
if ! command -v deno >/dev/null 2>&1; then
  echo "WARNING: deno not found on \$PATH. The source plugin runs via deno;"
  echo "install Deno 2.x (https://deno.com/) before SwiftBar can load it."
fi

# SwiftBar can live in /Applications, ~/Applications, or anywhere
# LaunchServices knows about. Warn but proceed: the wrapper is still
# valid once SwiftBar is installed.
if ! open -Ra "SwiftBar" >/dev/null 2>&1; then
  echo "WARNING: SwiftBar not detected. Install from https://swiftbar.app/"
fi

# A compiled binary install drops qmd-swiftbar (the binary) next to its
# own qmd.30s.sh wrapper. If the binary is present, the existing
# qmd.30s.sh is a real install, not ours, and overwriting it would break
# that install. Refuse below via the marker check; warn here.
if [ -e "$PLUGIN_DIR/qmd-swiftbar" ]; then
  echo "WARNING: a compiled binary install (qmd-swiftbar) is present in"
  echo "$PLUGIN_DIR. Remove it first to avoid duplicate icons / conflicts."
fi

mkdir -p "$PLUGIN_DIR"
remove_legacy_link

# Refuse to overwrite an existing qmd.30s.sh that we did not generate
# (for example, a binary-install wrapper).
if [ -e "$ENTRY" ] && ! is_our_wrapper "$ENTRY"; then
  echo "ERROR: $ENTRY exists and is not a dev wrapper we generated."
  echo "Refusing to overwrite it. Move or remove it first."
  exit 1
fi

# Make the source executable so its shebang can run when we exec it.
chmod +x "$SOURCE"

# Generate the wrapper atomically (write to temp, then mv into place).
#
# The shebang in qmd.30s.ts uses $HOME in --allow-read and --allow-write
# flags. Under launchd (SwiftBar's launcher), the kernel passes the
# shebang line to /usr/bin/env -S WITHOUT shell expansion — $HOME stays
# literal and Deno treats it as a filesystem path "$HOME/..." which doesn't
# exist. The wrapper works around this by constructing the deno command
# with fully-expanded paths, bypassing the broken shebang.
#
# Strategy: extract the deno flags from the source file's shebang,
# expand $HOME → actual home directory, prepend Homebrew to PATH, and
# exec deno directly. This keeps the shebang as the single source of
# truth for the flags while ensuring they work under launchd.
SHEBANG=$(head -1 "$SOURCE")
# Strip "#!/usr/bin/env -S deno run " prefix to get just the flags.
FLAGS=$(echo "$SHEBANG" | sed 's|^#!/usr/bin/env -S deno run ||')
# Expand $HOME to the actual home directory (available in launchd env).
FLAGS=$(echo "$FLAGS" | sed "s|\\\$HOME|${HOME}|g")

TMP_WRAPPER=$(mktemp)
trap 'rm -f "$TMP_WRAPPER"' EXIT
cat > "$TMP_WRAPPER" <<EOF
#!/bin/bash
$MARKER
# Delegates to the live working copy at the path below. Edit that file,
# not this one. Re-run scripts/dev-install.sh if the repo path changes.
#
# GUI apps (SwiftBar) are launched by launchd, which provides a minimal
# PATH (/usr/bin:/bin:/usr/sbin:/sbin) that excludes Homebrew. Prepend
# the Homebrew prefixes so deno (and qmd) resolve. Also, launchd does
# not expand \$HOME in shebangs, so we construct the deno command with
# fully-expanded paths here, bypassing the shebang.
export PATH="/opt/homebrew/bin:/usr/local/bin\${PATH:+:\$PATH}"
exec deno run $FLAGS "$SOURCE" "\$@"
EOF
chmod +x "$TMP_WRAPPER"
mv "$TMP_WRAPPER" "$ENTRY"
trap - EXIT

echo "Installed dev wrapper: $ENTRY"
echo "  delegates to: $SOURCE"
restart_hint
